#!/bin/bash

mostrarInfo()
{

	if [ $1 -eq 1 ]
	then
		dialog --title "EXISTE" --infobox "El usuario $i existe" 0 0
	else
		dialog --title "NO EXISTE" --infobox "El usuario $i no existe" 0 0
	fi

}
if [ $# -eq 0 ]
then
	dialog --infobox "ERR00R 404 --> Parámetro no introducido (./script parámetro)"
else
	for i in $*
	do
		for j in {1..100}
		do
			echo $j
			sleep 0.02
		done | dialog --title "IDENTIFICADOR" --gauge "Identificando usuario $i" 0 0
		id $i 2> /dev/null > /dev/null
		if [ $? -eq 0 ]
		then
			mostrarInfo 0
			sleep 2
		else
			mostrarInfo 1
			sleep 2
		fi

	done
	clear
fi
